version: "3.8"
services:
  unbound:
    build: .
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "853:853"
      - "8853:8853/udp"
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf
      - ./unbound_server.key:/etc/unbound/unbound_server.key
      - ./unbound_server.pem:/etc/unbound/unbound_server.pem
