name: Docker Image Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/guhill1/unbound:latest .
        docker push ghcr.io/guhill1/unbound:latest

    - name: Extract unbound binary from image
      run: |
        id=$(docker create ghcr.io/guhill1/unbound:latest)
        docker cp $id:/usr/local/sbin/unbound ./unbound
        docker rm $id

    - name: Upload unbound binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: unbound
        path: ./unbound
